### ISSUE TITLE
JDK Base Line

### ISSUE THREAD

**Issue by kameshsampath** [osgi/workspace#2]
Is there any specific reason why the "workspace" was base lined with JDK 8, is it possible to basline to JDK 7 ?

**Comment by pkriens** [comment]
The enRoute project will be 100% based on Java 8 … 

The reason is that the difference is too important to ignore. Lambdas have a tremendous influence on how one designs APIs. Since enRoute tries to demonstrate what can be done with OSGi it would be kind of throwing away a huge advantage.

Sorry for the inconvenience. Kind regards,

	Peter Kriens

**Comment by kameshsampath** [comment]
Oh I see, Thanks for clearing this up Peter.
